name: 'Action Called'

on:
  workflow_call:
    inputs:
      my-in:
        required: true
        type: string
    secrets:
      my-sec:
        required: true


jobs:
  demo-job-called:
    runs-on: ubuntu-latest
    steps:
    - name: 'Print'
      run: |
        echo "Input ${{ inputs.my-in }}"
        echo "Secret ${{ secrets.my-sec }}"
